/*Classe: enum de estilos musicais
 *Nome: Naomi Takemoto
 */

public enum EstiloMusical {
	ALTERNATIVO, CLASSICO, ELETRONICA, GOSPEL, HEAVY_METAL, HIP_HOP, RAP,
	INDIE, INSTRUMENTAL, J_POP, J_ROCK, JAZZ, JOVEM_GUARDA, K_POP, MPB, 
	NEW_AGE, PAGODE, POP, POP_ROCK, ROCK_PROGRESSIVO, RANDB, RAGGAE, ROCK,
	ROCK_AND_ROLL, SAMBA, ZAMBA, VELHA_GUARDA
}
